# SpendWise – Dataset Cleaning and Preprocessing

## Project
**SpendWise – AI-Powered Personal Expense Management & Prediction System**

## Objective
This notebook performs data inspection, cleaning, filtering, transformation, and feature engineering on the raw financial dataset.

The cleaned dataset will be used as the base dataset for the SpendWise machine learning system.

### Target Population
Young adults in India aged **18–35**.

### Primary Expense Categories
- Food
- Travel
- Entertainment
- Other Essentials

### Required Occupation Categories
- Student
- Salaried
- Self-employed/Business

## 1. Import Required Libraries

We use Pandas for loading, inspecting, cleaning, transforming, and saving the dataset.

In [43]:
import pandas as pd
import numpy as np

print("Libraries imported successfully.")

Libraries imported successfully.

## 2. Load the Raw Dataset

The original dataset is kept unchanged.

We will load it into a Pandas DataFrame called `df`.

In [44]:
df = pd.read_csv("raw_dataset.csv")

print("Dataset loaded successfully.")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Dataset loaded successfully.
Number of rows: 20000
Number of columns: 27

## 3. Display the First Five Records

This allows us to understand how the raw data is structured.

In [45]:
df.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Desired_Savings,Disposable_Income,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous
0,44637.249636,49,0,Self_Employed,Tier_1,13391.174891,0.000000,2206.490129,6658.768341,2636.970696,...,6200.537192,11265.627707,1685.696222,328.895281,465.769172,195.151320,678.292859,67.682471,0.000000,85.735517
1,26858.596592,34,2,Retired,Tier_2,5371.719318,0.000000,869.522617,2818.444460,1543.018778,...,1923.176434,9676.818733,540.306561,119.347139,141.866089,234.131168,286.668408,6.603212,56.306874,97.388606
2,50367.605084,35,1,Student,Tier_3,7555.140763,4612.103386,2201.800050,6313.222081,3221.396403,...,7050.360422,13891.450624,1466.073984,473.549752,410.857129,459.965256,488.383423,7.290892,106.653597,138.542422
3,101455.600247,21,0,Self_Employed,Tier_3,15218.340037,6809.441427,4889.418087,14690.149363,7106.130005,...,16694.965136,31617.953615,1875.932770,762.020789,1241.017448,320.190594,1389.815033,193.502754,0.000000,296.041183
4,24875.283548,52,4,Professional,Tier_2,4975.056710,3112.609398,635.907170,3034.329665,1276.155163,...,1874.099434,6265.700532,788.953124,68.160766,61.712505,187.173750,194.117130,47.294591,67.388120,96.557076

## 4. Display the Last Five Records

This is an additional check to understand the end of the dataset.

In [46]:
df.tail()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Desired_Savings,Disposable_Income,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous
19995,40913.466178,51,4,Self_Employed,Tier_1,12274.039853,7703.854895,1646.799940,5477.403246,2084.230191,...,1163.318310,1163.318310,597.028412,287.315050,347.658355,145.843671,212.833325,44.900294,98.765527,190.591917
19996,90295.772638,21,1,Student,Tier_2,18059.154528,0.000000,2770.589626,13118.222419,4633.108332,...,10613.589598,30725.175170,3854.823822,359.602765,911.269461,424.064224,1555.548024,129.655981,239.445622,351.436046
19997,40604.567373,30,1,Professional,Tier_2,8120.913475,8089.612716,1548.564328,6018.276121,2493.563674,...,2267.905134,2267.905134,1385.511100,379.927216,138.209465,297.695658,824.565267,57.891000,72.728663,122.569277
19998,118157.817240,27,2,Professional,Tier_1,35447.345172,12345.910538,4735.672471,16392.438426,8248.242279,...,10603.684814,10603.684814,3217.771594,2265.865033,726.247719,273.912367,859.230004,98.961780,92.189012,569.811212
19999,8209.249769,62,3,Professional,Tier_1,2462.774931,1120.881704,276.376556,969.916908,460.435438,...,531.044006,860.350559,261.160294,124.057428,25.940556,35.238134,94.909265,1.685026,4.837574,12.766302

## 5. Check Dataset Structure

We inspect:
- Column names
- Data types
- Number of non-null values

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Income                           20000 non-null  float64
 1   Age                              20000 non-null  int64
 2   Dependents                       20000 non-null  int64
 3   Occupation                       20000 non-null  str
 4   City_Tier                        20000 non-null  str
 5   Rent                             20000 non-null  float64
 6   Loan_Repayment                   20000 non-null  float64
 7   Insurance                        20000 non-null  float64
 8   Groceries                        20000 non-null  float64
 9   Transport                        20000 non-null  float64
 10  Eating_Out                       20000 non-null  float64
 11  Entertainment                    20000 non-null  float64
 12  Utilities                        20000 non-null  float64
 13  Healthcare                       20000 non-null  float64
 14  Education                        20000 non-null  float64
 15  Miscellaneous                    20000 non-null  float64
 16  Desired_Savings_Percentage       20000 non-null  float64
 17  Desired_Savings                  20000 non-null  float64
 18  Disposable_Income                20000 non-null  float64
 19  Potential_Savings_Groceries      20000 non-null  float64
 20  Potential_Savings_Transport      20000 non-null  float64
 21  Potential_Savings_Eating_Out     20000 non-null  float64
 22  Potential_Savings_Entertainment  20000 non-null  float64
 23  Potential_Savings_Utilities      20000 non-null  float64
 24  Potential_Savings_Healthcare     20000 non-null  float64
 25  Potential_Savings_Education      20000 non-null  float64
 26  Potential_Savings_Miscellaneous  20000 non-null  float64
dtypes: float64(23), int64(2), str(2)
memory usage: 4.4 MB

## 6. List All Columns

The raw dataset contains demographic information, monthly expenses, savings information, and potential savings variables.

In [48]:
print("Columns in the raw dataset:\n")

for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Columns in the raw dataset:

1. Income
2. Age
3. Dependents
4. Occupation
5. City_Tier
6. Rent
7. Loan_Repayment
8. Insurance
9. Groceries
10. Transport
11. Eating_Out
12. Entertainment
13. Utilities
14. Healthcare
15. Education
16. Miscellaneous
17. Desired_Savings_Percentage
18. Desired_Savings
19. Disposable_Income
20. Potential_Savings_Groceries
21. Potential_Savings_Transport
22. Potential_Savings_Eating_Out
23. Potential_Savings_Entertainment
24. Potential_Savings_Utilities
25. Potential_Savings_Healthcare
26. Potential_Savings_Education
27. Potential_Savings_Miscellaneous

## 7. Check Missing Values

Missing values can affect machine learning models.

We therefore check the number of missing values in every column.

In [49]:
missing_values = df.isnull().sum()

missing_table = pd.DataFrame({
    "Column": missing_values.index,
    "Missing_Values": missing_values.values
})

missing_table

                             Column  Missing_Values
0                            Income               0
1                               Age               0
2                        Dependents               0
3                        Occupation               0
4                         City_Tier               0
5                              Rent               0
6                    Loan_Repayment               0
7                         Insurance               0
8                         Groceries               0
9                         Transport               0
10                       Eating_Out               0
11                    Entertainment               0
12                        Utilities               0
13                       Healthcare               0
14                        Education               0
15                    Miscellaneous               0
16       Desired_Savings_Percentage               0
17                  Desired_Savings               0
18                Disposable_Income               0
19      Potential_Savings_Groceries               0
20      Potential_Savings_Transport               0
21     Potential_Savings_Eating_Out               0
22  Potential_Savings_Entertainment               0
23      Potential_Savings_Utilities               0
24     Potential_Savings_Healthcare               0
25      Potential_Savings_Education               0
26  Potential_Savings_Miscellaneous               0

In [50]:
print("Total missing values in the dataset:", df.isnull().sum().sum())

Total missing values in the dataset: 0

## 8. Check Duplicate Records

Duplicate records can cause certain users or observations to be overrepresented.

We check for exact duplicate rows.

In [51]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

## 9. Examine Age Distribution

SpendWise is designed for young adults.

Our project requirement is:

**Age between 18 and 35 years, inclusive.**

In [52]:
print("Minimum age:", df["Age"].min())
print("Maximum age:", df["Age"].max())

print("\nAge statistics:")
print(df["Age"].describe())

Minimum age: 18
Maximum age: 64

Age statistics:
count    20000.000000
mean        41.031450
std         13.578725
min         18.000000
25%         29.000000
50%         41.000000
75%         53.000000
max         64.000000
Name: Age, dtype: float64

In [53]:
age_groups = pd.cut(
    df["Age"],
    bins=[0, 17, 25, 30, 35, 40, 50, 65, 100],
    labels=[
        "Below 18",
        "18-25",
        "26-30",
        "31-35",
        "36-40",
        "41-50",
        "51-65",
        "Above 65"
    ],
    right=True
)

age_distribution = age_groups.value_counts().sort_index()

age_distribution.to_frame(name="Number_of_Records")

          Number_of_Records
Age
Below 18                  0
18-25                  3454
26-30                  2066
31-35                  2082
36-40                  2131
41-50                  4306
51-65                  5961
Above 65                  0

## 10. Filter the Target Age Group

The target population for SpendWise is young adults aged **18–35**.

Therefore, records outside this age range will be removed.

We use an inclusive range:

**18 ≤ Age ≤ 35**

In [54]:
original_row_count = len(df)

df = df[
    (df["Age"] >= 18) &
    (df["Age"] <= 35)
].copy()

filtered_row_count = len(df)

removed_rows = original_row_count - filtered_row_count

print("Rows before age filtering:", original_row_count)
print("Rows after age filtering:", filtered_row_count)
print("Rows removed:", removed_rows)

Rows before age filtering: 20000
Rows after age filtering: 7602
Rows removed: 12398

In [55]:
print("Age range after filtering:")
print("Minimum age:", df["Age"].min())
print("Maximum age:", df["Age"].max())

Age range after filtering:
Minimum age: 18
Maximum age: 35

## 11. Examine Occupation Categories

The raw dataset contains four occupation categories.

Our project requires three categories:

- Student
- Salaried
- Self-employed/Business

The original category `Professional` will be mapped to `Salaried`.

`Retired` will be removed because it is outside our defined project population.

In [56]:
occupation_table = df["Occupation"].value_counts().reset_index()

occupation_table.columns = [
    "Occupation",
    "Number_of_Records"
]

occupation_table

      Occupation  Number_of_Records
0        Student               1949
1  Self_Employed               1899
2        Retired               1896
3   Professional               1858

## 12. Remove the Retired Category

The `Retired` category is not part of our target occupation groups.

We therefore retain only:

- Student
- Professional
- Self_Employed

In [57]:
before_occupation_filter = len(df)

allowed_occupations = [
    "Student",
    "Professional",
    "Self_Employed"
]

df = df[
    df["Occupation"].isin(allowed_occupations)
].copy()

after_occupation_filter = len(df)

print("Rows before occupation filtering:", before_occupation_filter)
print("Rows after occupation filtering:", after_occupation_filter)
print("Rows removed:", before_occupation_filter - after_occupation_filter)

Rows before occupation filtering: 7602
Rows after occupation filtering: 5706
Rows removed: 1896

## 13. Standardize Occupation Names

The raw dataset uses `Professional` and `Self_Employed`.

For SpendWise, we use clearer project terminology:

- `Professional` → `Salaried`
- `Self_Employed` → `Self-employed/Business`
- `Student` → `Student`

In [58]:
occupation_mapping = {
    "Student": "Student",
    "Professional": "Salaried",
    "Self_Employed": "Self-employed/Business"
}

df["Occupation"] = df["Occupation"].replace(
    occupation_mapping
)

print(df["Occupation"].value_counts())

Occupation
Student                   1949
Self-employed/Business    1899
Salaried                  1858
Name: count, dtype: int64

## 14. Standardize City Tier

The raw dataset stores city tiers as:

- Tier_1
- Tier_2
- Tier_3

We standardize the naming format to:

- Tier 1
- Tier 2
- Tier 3

In [59]:
df["City_Tier"] = df["City_Tier"].str.replace(
    "_",
    " ",
    regex=False
)

city_tier_table = df["City_Tier"].value_counts().reset_index()

city_tier_table.columns = [
    "City_Tier",
    "Number_of_Records"
]

city_tier_table

  City_Tier  Number_of_Records
0    Tier 2               2895
1    Tier 1               1662
2    Tier 3               1149

## 15. Remove Unused Dependents Feature

The `Dependents` column is not required for the current scope of SpendWise.

It will therefore be removed from the cleaned dataset.

This removes the column only; no records are removed because of this feature.

In [60]:
df = df.drop(columns=["Dependents"])

print("Dependents column removed.")
print("Number of columns:", len(df.columns))

Dependents column removed.
Number of columns: 26

## 16. Validate Income Values

Income is an important feature for SpendWise.

We check for:
- Minimum income
- Maximum income
- Zero income
- Negative income
- Statistical distribution

In [61]:
print("Minimum income:", df["Income"].min())
print("Maximum income:", df["Income"].max())

print("\nZero income records:", (df["Income"] == 0).sum())
print("Negative income records:", (df["Income"] < 0).sum())

print("\nIncome statistics:")
df["Income"].describe()

Minimum income: 1393.5757735595796
Maximum income: 1079728.3735172302

Zero income records: 0
Negative income records: 0

Income statistics:

count    5.706000e+03
mean     4.221699e+04
std      4.372547e+04
min      1.393576e+03
25%      1.740403e+04
50%      3.004529e+04
75%      5.186998e+04
max      1.079728e+06
Name: Income, dtype: float64

## 17. Validate Expense Values

We check whether the major expense columns contain negative values.

Negative monthly expenses are not meaningful for our application and would indicate invalid records.

In [62]:
expense_columns = [
    "Rent",
    "Loan_Repayment",
    "Insurance",
    "Groceries",
    "Transport",
    "Eating_Out",
    "Entertainment",
    "Utilities",
    "Healthcare",
    "Education",
    "Miscellaneous"
]

negative_expenses = (df[expense_columns] < 0).sum()

negative_expense_table = negative_expenses.reset_index()

negative_expense_table.columns = [
    "Expense_Column",
    "Negative_Values"
]

negative_expense_table

    Expense_Column  Negative_Values
0             Rent                0
1   Loan_Repayment                0
2        Insurance                0
3        Groceries                0
4        Transport                0
5       Eating_Out                0
6    Entertainment                0
7        Utilities                0
8       Healthcare                0
9        Education                0
10   Miscellaneous                0

## 18. Create the Food Expense Category

SpendWise uses Food as one of its primary categories.

The raw dataset contains:

- Groceries
- Eating_Out

Therefore:

**Food Expense = Groceries + Eating Out**

In [63]:
df["Food_Expense"] = (
    df["Groceries"] +
    df["Eating_Out"]
)

df[
    [
        "Groceries",
        "Eating_Out",
        "Food_Expense"
    ]
].head()

       Groceries   Eating_Out  Food_Expense
2    6313.222081  1513.814376   7827.036457
3   14690.149363  5040.249158  19730.398521
9    5065.627032  2040.310666   7105.937697
10   3037.268327   451.411239   3488.679566
11   2597.398800   878.879491   3476.278291

## 19. Create the Travel Expense Category

The raw dataset contains `Transport`.

For SpendWise:

**Travel Expense = Transport**

In [64]:
df["Travel_Expense"] = df["Transport"]

df[
    [
        "Transport",
        "Travel_Expense"
    ]
].head()

      Transport  Travel_Expense
2   3221.396403     3221.396403
3   7106.130005     7106.130005
9   2500.054847     2500.054847
10  1459.275062     1459.275062
11  1123.038045     1123.038045

## 20. Create the Entertainment Expense Category

The raw dataset already contains an `Entertainment` expense.

For consistency, we create:

**Entertainment Expense = Entertainment**

In [65]:
df["Entertainment_Expense"] = df["Entertainment"]

df[
    [
        "Entertainment",
        "Entertainment_Expense"
    ]
].head()

    Entertainment  Entertainment_Expense
2     1723.306926            1723.306926
3     2858.194240            2858.194240
9     1016.613164            1016.613164
10     785.289634             785.289634
11     643.150518             643.150518

## 21. Review the Three Main SpendWise Expense Categories

SpendWise focuses on three primary expense categories:

1. Food
2. Travel
3. Entertainment

These categories are used to analyze the user's spending
behavior and will form the basis for future expense prediction.

In [66]:
category_columns = [
    "Food_Expense",
    "Travel_Expense",
    "Entertainment_Expense"
]

df[category_columns].head()

    Food_Expense  Travel_Expense  Entertainment_Expense
2    7827.036457     3221.396403            1723.306926
3   19730.398521     7106.130005            2858.194240
9    7105.937697     2500.054847            1016.613164
10   3488.679566     1459.275062             785.289634
11   3476.278291     1123.038045             643.150518

## 22. Calculate Total SpendWise Expense

Total SpendWise Expense represents the user's total spending
across the three expense categories included in the project.

Total Expense = Food + Travel + Entertainment

In [67]:
df["Total_Expense"] = (
    df["Food_Expense"]
    + df["Travel_Expense"]
    + df["Entertainment_Expense"]
)

df[
    [
        "Food_Expense",
        "Travel_Expense",
        "Entertainment_Expense",
        "Total_Expense"
    ]
].head()

    Food_Expense  Travel_Expense  Entertainment_Expense  Total_Expense
2    7827.036457     3221.396403            1723.306926   12771.739786
3   19730.398521     7106.130005            2858.194240   29694.722766
9    7105.937697     2500.054847            1016.613164   10622.605708
10   3488.679566     1459.275062             785.289634    5733.244263
11   3476.278291     1123.038045             643.150518    5242.466854

## 23. Calculate Actual Savings

Actual Savings represents the income remaining after
the user's SpendWise expenses.

Actual Savings = Income - Total Expense

In [68]:
df["Remaining_Income"] = (
    df["Income"] - df["Total_Expense"]
)

df[
    ["Income", "Total_Expense", "Remaining_Income"]
].head()

           Income  Total_Expense  Remaining_Income
2    50367.605084   12771.739786      37595.865298
3   101455.600247   29694.722766      71760.877481
9    46304.790235   10622.605708      35682.184527
10   20706.822336    5733.244263      14973.578073
11   20668.557390    5242.466854      15426.090536

## 24. Calculate Savings Rate

Savings Rate represents the percentage of income remaining
after the user's SpendWise expenses.

Savings Rate = (Actual Savings / Income) × 100

In [69]:
df["Remaining_Income_Percentage"] = (
    df["Remaining_Income"] / df["Income"]
) * 100

df[
    ["Income", "Remaining_Income", "Remaining_Income_Percentage"]
].head()

           Income  Remaining_Income  Remaining_Income_Percentage
2    50367.605084      37595.865298                    74.642948
3   101455.600247      71760.877481                    70.731312
9    46304.790235      35682.184527                    77.059381
10   20706.822336      14973.578073                    72.312293
11   20668.557390      15426.090536                    74.635545

## 25. Calculate Category-wise Spending Percentages

These percentages show how the user's SpendWise expenses
are distributed across Food, Travel, and Entertainment.

The three percentages together represent the user's
spending distribution across the project's primary categories.

In [70]:
df["Food_Percentage"] = (
    df["Food_Expense"] / df["Total_Expense"]
) * 100

df["Travel_Percentage"] = (
    df["Travel_Expense"] / df["Total_Expense"]
) * 100

df["Entertainment_Percentage"] = (
    df["Entertainment_Expense"] / df["Total_Expense"]
) * 100

df[
    [
        "Food_Percentage",
        "Travel_Percentage",
        "Entertainment_Percentage"
    ]
].head()

    Food_Percentage  Travel_Percentage  Entertainment_Percentage
2         61.284027          25.222847                 13.493126
3         66.444124          23.930616                  9.625260
9         66.894488          23.535232                  9.570281
10        60.850008          25.452867                 13.697125
11        66.309972          21.421939                 12.268089

## 26. Identify Overspending Users

An overspending flag is created when the user's total
SpendWise expense is greater than their income.

Overspending Flag:
- 1 = Total Expense > Income
- 0 = Total Expense <= Income

This feature can later be used to generate spending
warnings and financial alerts.

In [71]:
df["Overspending_Flag"] = (
    df["Total_Expense"] > df["Income"]
).astype(int)

print(
    "Number of overspending records:",
    df["Overspending_Flag"].sum()
)

print(
    "Overspending percentage:",
    round(
        df["Overspending_Flag"].mean() * 100,
        2
    ),
    "%"
)

Number of overspending records: 0
Overspending percentage: 0.0 %

In [72]:
df = df.drop(
    columns=["Overspending_Flag"],
    errors="ignore"
)

print("Overspending_Flag removed.")

Overspending_Flag removed.

## 27. Remove Expense Categories Outside the SpendWise Scope

The original dataset contains several additional financial
expense categories such as:

- Rent
- Loan Repayment
- Insurance
- Healthcare
- Education
- Utilities
- Miscellaneous

These categories are outside the primary scope of the
current SpendWise project.

SpendWise focuses specifically on:

- Food
- Travel
- Entertainment

Therefore, these additional expense columns are removed
from the cleaned modeling dataset.

In [73]:
excluded_expense_columns = [
    "Rent",
    "Loan_Repayment",
    "Insurance",
    "Utilities",
    "Healthcare",
    "Education",
    "Miscellaneous"
]

df = df.drop(
    columns=excluded_expense_columns,
    errors="ignore"
)

print("Excluded expense columns removed:")

for column in excluded_expense_columns:
    print("-", column)

print("\nCurrent number of columns:", len(df.columns))

Excluded expense columns removed:
- Rent
- Loan_Repayment
- Insurance
- Utilities
- Healthcare
- Education
- Miscellaneous

Current number of columns: 28

## 28. Remove Derived Financial Columns

The original dataset contains Disposable Income and Potential
Savings columns.

These values are derived from other financial information
and may introduce data leakage into the machine learning model.

Therefore, they are removed from the cleaned modeling dataset.

In [74]:
derived_columns = [
    "Disposable_Income",
    "Potential_Savings_Groceries",
    "Potential_Savings_Transport",
    "Potential_Savings_Eating_Out",
    "Potential_Savings_Entertainment",
    "Potential_Savings_Utilities",
    "Potential_Savings_Healthcare",
    "Potential_Savings_Education",
    "Potential_Savings_Miscellaneous"
]

df = df.drop(
    columns=derived_columns,
    errors="ignore"
)

print("Derived financial columns removed.")

print("\nCurrent number of columns:", len(df.columns))

Derived financial columns removed.

Current number of columns: 19

## 29. Final SpendWise Dataset Structure

In [75]:
print("Final number of rows:", df.shape[0])
print("Final number of columns:", df.shape[1])

print("\nFinal columns:")

for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Final number of rows: 5706
Final number of columns: 19

Final columns:
1. Income
2. Age
3. Occupation
4. City_Tier
5. Groceries
6. Transport
7. Eating_Out
8. Entertainment
9. Desired_Savings_Percentage
10. Desired_Savings
11. Food_Expense
12. Travel_Expense
13. Entertainment_Expense
14. Total_Expense
15. Remaining_Income
16. Remaining_Income_Percentage
17. Food_Percentage
18. Travel_Percentage
19. Entertainment_Percentage

## 30. Final Data Quality Validation

In [76]:
remaining_expense_columns = [
    "Groceries",
    "Eating_Out",
    "Transport",
    "Entertainment"
]

print("========== FINAL DATA QUALITY REPORT ==========\n")

print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

print("\nMissing values:",
      df.isnull().sum().sum())

print("Duplicate rows:",
      df.duplicated().sum())

print(
    "\nAge range:",
    df["Age"].min(),
    "to",
    df["Age"].max()
)

print("\nOccupation categories:")
print(df["Occupation"].value_counts())

print("\nCity Tier categories:")
print(df["City_Tier"].value_counts())

print(
    "\nNegative expense values:",
    (df[remaining_expense_columns] < 0).sum().sum()
)

print(
    "\nIncome <= 0 records:",
    (df["Income"] <= 0).sum()
)

print("\n==============================================")

========== FINAL DATA QUALITY REPORT ==========

Number of rows: 5706
Number of columns: 19

Missing values: 0
Duplicate rows: 0

Age range: 18 to 35

Occupation categories:
Occupation
Student                   1949
Self-employed/Business    1899
Salaried                  1858
Name: count, dtype: int64

City Tier categories:
City_Tier
Tier 2    2895
Tier 1    1662
Tier 3    1149
Name: count, dtype: int64

Negative expense values: 0

Income <= 0 records: 0

==============================================

## 31. Display the Final Cleaned Dataset

In [77]:
df.head(10)

,Income,Age,Occupation,City_Tier,Groceries,Transport,Eating_Out,Entertainment,Desired_Savings_Percentage,Desired_Savings,Food_Expense,Travel_Expense,Entertainment_Expense,Total_Expense,Remaining_Income,Remaining_Income_Percentage,Food_Percentage,Travel_Percentage,Entertainment_Percentage
2,50367.605084,35,Student,Tier 3,6313.222081,3221.396403,1513.814376,1723.306926,13.997808,7050.360422,7827.036457,3221.396403,1723.306926,12771.739786,37595.865298,74.642948,61.284027,25.222847,13.493126
3,101455.600247,21,Self-employed/Business,Tier 3,14690.149363,7106.130005,5040.249158,2858.194240,16.455440,16694.965136,19730.398521,7106.130005,2858.194240,29694.722766,71760.877481,70.731312,66.444124,23.930616,9.625260
9,46304.790235,30,Student,Tier 2,5065.627032,2500.054847,2040.310666,1016.613164,12.126401,5615.104745,7105.937697,2500.054847,1016.613164,10622.605708,35682.184527,77.059381,66.894488,23.535232,9.570281
10,20706.822336,31,Student,Tier 3,3037.268327,1459.275062,451.411239,785.289634,8.353299,1729.702763,3488.679566,1459.275062,785.289634,5733.244263,14973.578073,72.312293,60.850008,25.452867,13.697125
11,20668.557390,31,Salaried,Tier 2,2597.398800,1123.038045,878.879491,643.150518,8.245344,1704.193686,3476.278291,1123.038045,643.150518,5242.466854,15426.090536,74.635545,66.309972,21.421939,12.268089
17,38574.647021,21,Salaried,Tier 2,5126.823467,2614.478029,1267.553419,1802.739439,6.911498,2666.085960,6394.376887,2614.478029,1802.739439,10811.594354,27763.052666,71.972279,59.143700,24.182169,16.674131
26,11946.071980,19,Student,Tier 2,1363.786116,641.888253,475.929401,497.306250,5.612336,670.453708,1839.715517,641.888253,497.306250,2978.910019,8967.161961,75.063686,61.758009,21.547756,16.694235
37,6255.501287,33,Self-employed/Business,Tier 2,841.285098,457.474951,234.345218,301.519762,6.422917,401.785682,1075.630317,457.474951,301.519762,1834.625029,4420.876258,70.671814,58.629437,24.935610,16.434953
38,10367.216239,23,Student,Tier 3,1072.111538,763.019588,292.243613,237.309738,6.303268,653.473451,1364.355151,763.019588,237.309738,2364.684477,8002.531762,77.190748,57.697133,32.267290,10.035577
40,54161.517425,23,Self-employed/Business,Tier 1,6609.118734,4218.097163,1305.236358,2483.219612,10.878081,5174.202076,7914.355091,4218.097163,2483.219612,14615.671866,39545.845559,73.014656,54.149786,28.860098,16.990116

## 32. Save the Cleaned SpendWise Dataset

In [78]:
output_file = "spendwise_cleaned_dataset.csv"

df.to_csv(
    output_file,
    index=False
)

print("Cleaned dataset saved successfully!")
print("File:", output_file)

Cleaned dataset saved successfully!
File: spendwise_cleaned_dataset.csv

# Conclusion

The dataset has been cleaned and prepared according to the
scope of the SpendWise project.

The following preprocessing steps were performed:

- Restricted users to the target age group of 18–35 years.
- Removed the Retired occupation category.
- Standardized occupation names.
- Standardized city-tier values.
- Removed the Dependents column.
- Created three primary expense categories:
  - Food
  - Travel
  - Entertainment
- Calculated Total SpendWise Expense.
- Calculated Actual Savings.
- Calculated Savings Rate.
- Calculated category-wise spending percentages.
- Created an Overspending Flag.
- Removed expense categories outside the project scope.
- Removed derived financial columns that may cause data leakage.
- Validated missing values, duplicate records, income values,
  and negative expense values.
- Saved the final cleaned dataset as
  `spendwise_cleaned_dataset.csv`.

The resulting dataset is now ready for the next stage of the
SpendWise project: feature engineering and preparation for
machine learning.